# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MMS-Mail-Message-Parsed
version:      0.03
version_from: lib/MMS/Mail/Message/Parsed.pm
installdirs:  site
requires:
    MMS::Mail::Message:            0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
